---
- name: start httpd if it's stopped
  hosts: node-1
  become: yes
  tasks:
    - name: check httpd processes is running
      shell: ps -ef |grep http[d]
      register: ret
      ignore_errors: yes
      changed_when: no

    - name: print return value
      debug:
        var: ret

    - name: start httpd (httpd is stopped)
      service:
        name: httpd
        state: started
      when:
        - ret.rc == 1
