---
sudo: required
language: python
python:
  - "3.6"
services:
  - docker

before_install:
  # Prepare Travis environment
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5

  # Required packages
  - sudo apt install -y sshpass jq

  # Install Ansible
  - pip install -U pip setuptools
  - pip install ansible

script:
  - ansible --version
  - pwd
  - tree .
  - echo ### prepare environment
  - cd master-course-data/assets/tools
  - ansible-playbook -i localhost, -c local kata_prepare.yml

notifications:
  email: false
